apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata-todo-postgres-0
  namespace: project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
