apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv-project
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /tmp/kube/project-shared
  claimRef:
    namespace: project
    name: shared-pvc
